In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\data sets\fraud_data.csv",encoding="ANSI")
df

V1        V2        V3        V4        V5        V6        V7  \
0      1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1      0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2      1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3     -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4     -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   
...         ...       ...       ...       ...       ...       ...       ...   
21688 -3.959670  3.297819 -1.079436 -2.290106 -1.405133  2.452586 -4.649235   
21689 -1.066503  0.539240  0.735343 -0.506800  0.843980 -1.047877  1.141302   
21690 -2.175162 -0.441681  1.883137 -0.267440  1.056972  0.136404  0.113595   
21691  0.031406  0.694817  0.083233 -0.797912  0.564318 -0.560787  0.805901   
21692 -0.312369  0.944738  1.430605  0.627951  0.317725 -0.180406  0.793108   

              V8        V9       V10  ...        V21       V22       V23  \
0      -0.069246 -0.266389  0.155315  ...  -0.109627 -0.341365  0.057845   
1      -0.626979 -2.274423  1.527782  ...   0.652202  0.272684 -0.982151   
2       0.173310 -0.808999  0.775436  ...  -0.003802  0.058556 -0.121177   
3      -0.007181 -0.165760  0.869659  ...   0.130648  0.329445  0.927656   
4       0.670674 -0.442658  0.133499  ...  -0.312774 -0.799494 -0.064488   
...          ...       ...       ...  ...        ...       ...       ...   
21688 -12.365464  0.409493  1.251992  ...  12.617463 -2.969195  1.755050   
21689  -0.127448 -0.119221 -1.870265  ...  -0.162535 -0.576352 -0.184969   
21690  -0.055983  0.765616 -0.087568  ...  -0.201561  0.397761 -0.855500   
21691   0.051453 -0.053817 -0.200190  ...  -0.255891 -0.664635  0.018844   
21692  -0.104993 -0.493956  0.344477  ...   0.118417  0.609081 -0.270644   

            V24       V25       V26       V27       V28  Amount  Class  
0      0.499180  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1      0.165900  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2     -0.304215  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3     -0.049560 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4      0.953062 -0.429550  0.158225  0.076943 -0.015051    2.67      0  
...         ...       ...       ...       ...       ...     ...    ...  
21688  0.433324 -0.010827 -0.126613  0.200111 -0.160542   29.95      0  
21689 -0.136154  0.760012  0.048105 -0.017475  0.092365   85.66      0  
21690 -0.627900  0.590977  0.515065  0.433089 -0.150291  131.10      0  
21691 -0.539177 -0.504019  0.155133  0.232846  0.079420    4.49      0  
21692  0.004333 -0.114185 -0.287989  0.232375 -0.023563   14.90      0  

[21693 rows x 30 columns]

In [3]:
df.head(5)

V1        V2        V3        V4        V5        V6        V7  \
0  1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1  0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2  1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3 -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4 -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0 -0.069246 -0.266389  0.155315  ... -0.109627 -0.341365  0.057845  0.499180   
1 -0.626979 -2.274423  1.527782  ...  0.652202  0.272684 -0.982151  0.165900   
2  0.173310 -0.808999  0.775436  ... -0.003802  0.058556 -0.121177 -0.304215   
3 -0.007181 -0.165760  0.869659  ...  0.130648  0.329445  0.927656 -0.049560   
4  0.670674 -0.442658  0.133499  ... -0.312774 -0.799494 -0.064488  0.953062   

        V25       V26       V27       V28  Amount  Class  
0  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4 -0.429550  0.158225  0.076943 -0.015051    2.67      0  

[5 rows x 30 columns]

In [4]:
df.isnull().sum()

V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
df["Class"].unique()

array([0, 1], dtype=int64)

In [6]:
x=df[["V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","V11","V12","V13","V14","V15","V16","V17","V18","V19","V20","V21","V22","V23","V24","V25","V26","V27","V28","Amount"]].values
y=df[["Class"]].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size =0.7)

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train.ravel())
y_pred=lr.predict(x_test)

C:\Users\raghvendra\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [8]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [10]:
accuracy_score(y_pred,y_test)

0.9953902888752305

In [11]:
confusion_matrix(y_pred,y_test)

array([[6393,   27],
       [   3,   85]], dtype=int64)